apiVersion: batch/v1
kind: Job
metadata:
  name: propose-request
spec:
  template:
    metadata:
      labels:
        app: request
    spec:
      restartPolicy: OnFailure
      containers:
      - name: request-proposer
        image: avalon-shell-dev:latest
        imagePullPolicy: Never
        command: ["/bin/bash"]
        args: ["/project/avalon/scripts/propose_requests.sh"]
